[DEFAULT]
main-repo = gentoo

[gentoo]
location = /var/db/repos/gentoo
sync-type = rsync
sync-uri = rsync://rsync.gentoo.org/gentoo-portage
auto-sync = yes

[cosmic-overlay]
location = /var/db/repos/cosmic-overlay
sync-type = git
sync-uri = https://github.com/fsvm88/cosmic-overlay.git
auto-sync = yes

[regicide-rust]
location = /var/db/repos/regicide-rust
sync-type = git
sync-uri = https://github.com/awdemos/RegicideOS.git
auto-sync = yes
