# BtrMind Configuration File
# AI-powered BTRFS storage monitoring and optimization

[monitoring]
# Path to monitor for BTRFS usage
target_path = "/tmp"

# How often to collect metrics (seconds)
poll_interval = 60

# Window for trend analysis (hours)
trend_analysis_window = 24

[thresholds]
# Disk usage percentage thresholds
warning_level = 85.0    # Start monitoring more closely
critical_level = 95.0   # Begin aggressive cleanup
emergency_level = 98.0  # Emergency actions

[actions]
# Enable/disable specific cleanup actions
enable_compression = true
enable_balance = true
enable_snapshot_cleanup = true
enable_temp_cleanup = true

# Paths to clean during temp cleanup
temp_paths = [
    "/tmp",
    "/var/tmp", 
    "/var/cache",
    "/home/*/.cache"
]

# Number of snapshots to keep
snapshot_keep_count = 10

[learning]
# Path to store the AI model
model_path = "/var/lib/btrmind/model.safetensors"

# How often to update the model (seconds)
model_update_interval = 3600

# Reward smoothing factor (0.0 - 1.0)
reward_smoothing = 0.95

# Exploration rate for action selection (0.0 - 1.0)
exploration_rate = 0.1

# Learning rate for neural network updates
learning_rate = 0.001

# Discount factor for future rewards
discount_factor = 0.99

[fragmentation_model]
# Path to fragmentation model JSON file
model_path = "/etc/btrmind/fragmentation_model.json"

# Enable MLE model vs heuristic fallback
use_model = true

# Enable training data collection
enable_data_collection = false

# Path to training data CSV
training_data_path = "/var/lib/btrmind/training_data.csv"

# Minimum samples required for training
min_samples_for_training = 500

# Fallback to heuristic if model fails
fallback_to_heuristic = true

# Model prediction timeout (ms)
prediction_timeout_ms = 100

# Global dry-run mode (for testing)
dry_run = false
