import os
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from regicide_update import boot_entry, common as rc, root_ab


class BootEntryTests(unittest.TestCase):
    def setUp(self):
        self.tmpdir = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmpdir.cleanup)
        self.boot_patch = mock.patch.object(boot_entry, "ESP_BOOT_DIR", Path(self.tmpdir.name))
        self.boot_patch.start()
        self.addCleanup(self.boot_patch.stop)

        roots_dir = os.path.join(self.tmpdir.name, "roots")
        os.makedirs(roots_dir)
        self.roots_patch = mock.patch.object(rc, "ROOTS_DIR", roots_dir)
        self.roots_patch.start()
        self.addCleanup(self.roots_patch.stop)
        root_ab.CURRENT_FILE = Path(roots_dir) / ".regicide-root-current"

        self._orig_pretend = rc.PRETEND
        rc.PRETEND = True
        self.addCleanup(setattr, rc, "PRETEND", self._orig_pretend)

    def _make_slot_boot_dir(self, slot: str, kernel: str, initrd: str):
        boot_dir = os.path.join(rc.ROOTS_DIR, f"roots_{slot}", "boot")
        os.makedirs(boot_dir, exist_ok=True)
        Path(os.path.join(boot_dir, kernel)).touch()
        Path(os.path.join(boot_dir, initrd)).touch()

    def _slot_kernel_path(self, slot: str, name: str) -> str:
        return f"/roots/roots_{slot}/boot/{name}"

    def test_ensure_grub_cfg_creates_dispatch_and_stub(self):
        self._make_slot_boot_dir("a", "vmlinuz-6.8.0-gentoo", "initramfs-6.8.0-gentoo.img")
        self._make_slot_boot_dir("b", "vmlinuz-6.9.0-gentoo", "initramfs-6.9.0-gentoo.img")
        boot_entry.ensure_grub_cfg()
        dispatch = boot_entry._grub_dispatch()
        self.assertTrue(dispatch.is_file())
        text = dispatch.read_text()
        self.assertIn(boot_entry._DISPATCH_MARKER, text)
        self.assertIn("insmod btrfs", text)
        self.assertIn("search --label ROOTS --set=root", text)
        # Menuentries use the fs-relative subvolume path and the discovered
        # versioned kernel/initrd basenames.
        self.assertIn("linux /roots_a/boot/vmlinuz-6.8.0-gentoo", text)
        self.assertIn("initrd /roots_a/boot/initramfs-6.8.0-gentoo.img", text)
        self.assertIn("root=LABEL=ROOTS ro rootflags=subvol=roots_a", text)
        self.assertIn("linux /roots_b/boot/vmlinuz-6.9.0-gentoo", text)
        self.assertIn('menuentry "RegicideOS (a)" --id=regicide-a', text)
        # The main grub.cfg only sources the dispatch.
        cfg = boot_entry._grub_cfg()
        self.assertTrue(cfg.is_file())
        self.assertIn("source $prefix/regicide.cfg", cfg.read_text())

    def test_ensure_grub_cfg_keeps_existing_mkconfig_entries(self):
        cfg = boot_entry._grub_cfg()
        cfg.parent.mkdir(parents=True, exist_ok=True)
        cfg.write_text("set default=0\n# generated by grub-mkconfig\n")
        boot_entry.ensure_grub_cfg()
        text = cfg.read_text()
        self.assertIn("# generated by grub-mkconfig", text)
        self.assertIn("source $prefix/regicide.cfg", text)

    def test_ensure_grub_cfg_is_idempotent(self):
        boot_entry.ensure_grub_cfg()
        dispatch = boot_entry._grub_dispatch()
        # Manually append noise; ensure_grub_cfg should leave it alone.
        with open(dispatch, "a") as f:
            f.write("# extra\n")
        boot_entry.ensure_grub_cfg()
        self.assertIn("# extra", dispatch.read_text())

    def test_discover_kernel_initrd_finds_versioned_names(self):
        self._make_slot_boot_dir("a", "vmlinuz-6.8.0-gentoo", "initramfs-6.8.0-gentoo.img")
        kernel, initrd = boot_entry.discover_kernel_initrd("a")
        self.assertEqual(kernel, "vmlinuz-6.8.0-gentoo")
        self.assertEqual(initrd, "initramfs-6.8.0-gentoo.img")

    def test_discover_kernel_initrd_prefers_stable_names(self):
        boot_dir = os.path.join(rc.ROOTS_DIR, "roots_a", "boot")
        os.makedirs(boot_dir, exist_ok=True)
        Path(os.path.join(boot_dir, "vmlinuz-6.8.0-gentoo")).touch()
        Path(os.path.join(boot_dir, "vmlinuz")).touch()
        Path(os.path.join(boot_dir, "initramfs-6.8.0-gentoo.img")).touch()
        Path(os.path.join(boot_dir, "initramfs.img")).touch()
        kernel, initrd = boot_entry.discover_kernel_initrd("a")
        self.assertEqual(kernel, "vmlinuz")
        self.assertEqual(initrd, "initramfs.img")

    def test_discover_kernel_initrd_is_deterministic_with_many_files(self):
        boot_dir = os.path.join(rc.ROOTS_DIR, "roots_a", "boot")
        os.makedirs(boot_dir, exist_ok=True)
        # 6.9.10 is alphabetically/length-wise LOWER than 6.10.1 but
        # numerically higher; the version sort must pick 6.10.1.
        for name in ["vmlinuz-6.9.10-gentoo", "vmlinuz-6.9.9-gentoo", "vmlinuz-6.10.1-gentoo"]:
            Path(os.path.join(boot_dir, name)).touch()
        for name in ["initramfs-6.9.10-gentoo.img", "initramfs-6.9.9-gentoo.img", "initramfs-6.10.1-gentoo.img"]:
            Path(os.path.join(boot_dir, name)).touch()
        kernel, initrd = boot_entry.discover_kernel_initrd("a")
        self.assertEqual(kernel, "vmlinuz-6.10.1-gentoo")
        self.assertEqual(initrd, "initramfs-6.10.1-gentoo.img")

    def test_write_slot_to_grubenv_rejects_invalid_slot(self):
        with self.assertRaises(SystemExit):
            boot_entry.write_slot_to_grubenv("c")

    @mock.patch.object(boot_entry, "_grub_editenv")
    def test_write_slot_to_grubenv_sets_slot(self, mock_editenv):
        boot_entry._init_grubenv()
        boot_entry.write_slot_to_grubenv("b")
        mock_editenv.assert_called_once_with(["set", "regicide_slot=b"])

    def test_write_slot_to_grubenv_restores_backup_on_failure(self):
        boot_entry._init_grubenv()
        env_path = boot_entry._grubenv_path()
        env_path.write_text("# existing block\n")

        def boom(*args, **kwargs):
            raise RuntimeError("disk full")

        with mock.patch.object(boot_entry, "_grub_editenv", side_effect=boom):
            with self.assertRaises(RuntimeError):
                boot_entry.write_slot_to_grubenv("b")
        self.assertIn("# existing block", env_path.read_text())

    @mock.patch.object(boot_entry, "_grub_editenv")
    def test_sync_entries_sets_active_slot(self, mock_editenv):
        root_ab.write_active_slot("b")
        self._make_slot_boot_dir("a", "vmlinuz-a", "initramfs-a.img")
        self._make_slot_boot_dir("b", "vmlinuz-b", "initramfs-b.img")
        boot_entry.sync_entries()
        mock_editenv.assert_called_once_with(["set", "regicide_slot=b"])

    @mock.patch.object(boot_entry, "_grub_editenv")
    def test_sync_entries_warns_when_standby_slot_unbootable(self, mock_editenv):
        """An unbootable standby slot must not block updating the active one."""
        root_ab.write_active_slot("b")
        self._make_slot_boot_dir("b", "vmlinuz-b", "initramfs-b.img")
        os.makedirs(os.path.join(rc.ROOTS_DIR, "roots_a"))
        boot_entry.sync_entries()
        mock_editenv.assert_called_once_with(["set", "regicide_slot=b"])

    @mock.patch.object(boot_entry, "_grub_editenv")
    def test_sync_entries_dies_when_active_slot_unbootable(self, mock_editenv):
        root_ab.write_active_slot("a")
        self._make_slot_boot_dir("b", "vmlinuz-b", "initramfs-b.img")
        os.makedirs(os.path.join(rc.ROOTS_DIR, "roots_a"))
        with self.assertRaises(SystemExit):
            boot_entry.sync_entries()
        mock_editenv.assert_not_called()

    def test_sync_entries_discovers_both_slots(self):
        root_ab.write_active_slot("b")
        self._make_slot_boot_dir("a", "vmlinuz-a", "initramfs-a.img")
        self._make_slot_boot_dir("b", "vmlinuz-b", "initramfs-b.img")
        boot_entry.ensure_grub_cfg()
        # Real discovery; should not raise.
        boot_entry.sync_entries()

    def test_read_slot_from_grubenv_missing_returns_none(self):
        self.assertIsNone(boot_entry.read_slot_from_grubenv())

    def test_read_slot_from_grubenv_parses_slot(self):
        env_path = boot_entry._grubenv_path()
        env_path.parent.mkdir(parents=True, exist_ok=True)
        env_path.write_text("# GRUB Environment Block\nregicide_slot=b\n")
        self.assertEqual(boot_entry.read_slot_from_grubenv(), "b")

    def test_read_slot_from_grubenv_unreadable_dies(self):
        env_path = boot_entry._grubenv_path()
        env_path.parent.mkdir(parents=True, exist_ok=True)
        os.makedirs(env_path)  # a directory cannot be read as a file
        with self.assertRaises(SystemExit):
            boot_entry.read_slot_from_grubenv()

    def test_install_and_sync_activates_slot_and_updates_grub(self):
        from regicide_update import boot_entry as be

        image_path = Path(self.tmpdir.name) / "new-root.tar.xz"
        image_path.write_text("")
        order = []

        with mock.patch.object(root_ab, "install_image", return_value="b"):
            with mock.patch.object(
                be, "write_slot_to_grubenv", side_effect=lambda s: order.append(("grubenv", s))
            ):
                with mock.patch.object(
                    root_ab, "activate_slot", side_effect=lambda s: order.append(("activate", s))
                ):
                    with mock.patch.object(be, "ensure_grub_cfg"):
                        slot = be.install_and_sync(image_path)
        self.assertEqual(slot, "b")
        # grubenv must be written BEFORE the CURRENT_FILE marker so a crash
        # in between fails safe toward the previously verified slot.
        self.assertEqual(order, [("grubenv", "b"), ("activate", "b")])

    def test_rollback_and_sync_switches_default(self):
        from regicide_update import boot_entry as be

        root_ab.CURRENT_FILE.write_text("b\n")
        with mock.patch.object(root_ab, "rollback", return_value="a"):
            with mock.patch.object(be, "write_slot_to_grubenv") as mock_grubenv:
                with mock.patch.object(be, "ensure_grub_cfg"):
                    slot = be.rollback_and_sync()
        self.assertEqual(slot, "a")
        mock_grubenv.assert_called_once_with("a")


if __name__ == "__main__":
    unittest.main()
